**Bienvenue dans ce Jupyter Notebook destiné à effectuer une analyse des sentiments à partir d'un dataset en Python**

In [1]:
!pip install nltk

Requirement already satisfied: nltk in /home/joris/anaconda3/lib/python3.13/site-packages (3.9.2)
Requirement already satisfied: click in /home/joris/anaconda3/lib/python3.13/site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /home/joris/anaconda3/lib/python3.13/site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /home/joris/anaconda3/lib/python3.13/site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in /home/joris/anaconda3/lib/python3.13/site-packages (from nltk) (4.67.1)

In [65]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
import re
import string

nltk.download('stopwords')  # Pour les mots vides
nltk.download('punkt_tab')  # Pour la tokenisation (déjà fait normalement)
nltk.download('wordnet')    # Pour la lemmatisation (notre prochaine étape !)

[nltk_data] Downloading package stopwords to /home/joris/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/joris/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /home/joris/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [66]:
df = pd.read_csv('IMDB_Dataset.csv')

In [67]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [68]:
df.shape

(50000, 2)

**Data Preprocessing**

In [69]:
mapping = {'positive': 1, 'negative': 0}

df['sentiment'] = df['sentiment'].map(mapping)

df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [70]:
df.value_counts

<bound method DataFrame.value_counts of                                                   review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production. <br /><br />The...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically there's a family where a little boy ...          0
4      Petter Mattei's "Love in the Time of Money" is...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  I'm going to have to disagree with the previou...          0
49999  No one expects the Star Trek movies to be high...          0

[50000 rows x 2 columns]>

In [71]:
print(df['review'].value_counts())
print(df['sentiment'].value_counts())

review
Loved today's show!!! It was a variety and not solely cooking (which would have been great too). Very stimulating and captivating, always keeping the viewer peeking around the corner to see what was coming up next. She is as down to earth and as personable as you get, like one of us which made the show all the more enjoyable. Special guests, who are friends as well made for a nice surprise too. Loved the 'first' theme and that the audience was invited to play along too. I must admit I was shocked to see her come in under her time limits on a few things, but she did it and by golly I'll be writing those recipes down. Saving time in the kitchen means more time with family. Those who haven't tuned in yet, find out what channel and the time, I assure you that you won't be disappointed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        5
Hilarious, clean, light-hearted, and quote-worthy. What else can you ask for in a film? This is my all-time, number one favorite movie. Ever since I was a little girl, I've dreamed of owning a blue van with flames and an observation bubble.<br /><br />The cliché characters in ridiculous situations are what make this film such great fun. The wonderful comedic chemistry between Stephen Furst (Harold) and Andy Tennant (Melio) make up most of my favorite parts of the movie. And who didn't love the hopeless awkwardness of Flynch? Don't forget the airport antics of Leon's cronies, dressed up as Hari Krishnas: dancing, chanting and playing the tambourine--unbeatable! The clues are genius, the locations are classic, and the plot is timeless.<br /><br />A word to the wise, if you didn't watch this film when you were little, it probably won't win a place in your heart today. But nevertheless give it a chance, you may find that "It doesn't matter what you say, it doesn't matter what you do, you've gotta play."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          4
You do realize that you've been watching the EXACT SAME SHOW for eight years, right? I could understand the initial curiosity of seeing strangers co-exist on an Island, but you'd think that after watching unkempt, stink-ladened heroes run roughshod through the bush with an egg on a spoon for half a decade would be enough to get you to commit to something a little more original (and interesting).<br /><br />And I'm not even speaking of the shows validity which for the record I find questionable. It's just hard to suspend disbelief for "Bushy Bill" eating a rat when the entire crew of producers and camera people are housed in an air conditioned make-shift bio-dome sipping frosty mochcinno's with moxy.<br /><br />What's the appeal here? I don't care about these people or their meandering lives. I just don't get it. But if you DO find yourself being captivated by hairy, unwashed people, I suggest you turn off your TV and just take a trip to your local bus station where you can see people like this in their TRUE habitat. They call them HOMELESS PEOPLE, and free of charge, you can sit back and marvel in their uncanny ability to retrieve various cigarette debris from a plethora of garbage canisters, eventually striking "pay-dirt" and fashioning a homemade Dr. Frankenstein-styled cancer-stick, all the while begging people for change for food when the stink of "Aqua Velva" on their breath is enough to suggest otherwise. And the best part? Much like Survivor, every week one member of the tribe "Leaves" the "Island" when they are unceremoniously sent packing to the local Institution when the frightening unmedicated state of full-blown schizophrenia kicks into gear! Now THAT'S ENTERTAINMENT!    3
I see that C. Thomas Howell has appeared in many movies since his heyday in the 80s as an accomplished young actor.<br /><br />I bought this DVD because it was cheap and in part for the internet-related plot and to see how much older C. Thomas Howell is; I do not recall seeing him in any movies since the 1980s.<br /><br />In just a few words: what a very big disappointment. I give some low budget movies a chance, but this one started out lame. Within the first 15 minutes of the movie, this elusive woman is chatting with an Asian guy in a chatroom. They basically stimulate themselves to their own chat, she then insists on meeting the participant in person. She meets him, has sex, ties him up and then murders him in cold blood. The plot then deteriorates further.<br /><br />The plot is thin and flimsy and the acting is very stiff. Do not bother renting it much less purchasing it, even if it is in the $1 DVD bin. I plan to take my copy of the DVD to Goodwill. I am truly amazed that any of the prior reviewers here gave this movie a bad rating.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 3
When i got this movie free from my job, along with three other similar movies.. I watched then with very low expectations. Now this movie isn't bad per se. You get what you pay for. It is a tale of love, betrayal, lies, sex, scandal, everything you want in a movie. Definitely not a Hollywood blockbuster, but for cheap thrills it is not that bad. I would probably never watch this movie again. In a nutshell this is the kind of movie that you would see either very late at night on a local television station that is just wanting to take up some time, or you would see it on a Sunday afternoon on a local television station that is trying to take up some time. Despite the bad acting, cliché lines, and sub par camera work. I didn't have the desire to turn off the movie and pretend like it never popped into my DVD player. The story has been done many times in many movies. This one is no different, no better, no worse. <br /><br />Just your average movie.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
At least among those movies with 100 votes or more. Nominated for best screenplay written directly for the screen? Brenda Blethyn nominated for best actress in a leading role?? Nominated for best picture?? I always disagree with many of the Oscar picks, but this movie might very well be the worst movie of all time to be honored by the Academy. The writing and acting were both horrible. Blethyn's perfomance in particular was one of the worst I've ever seen, and probably the most over-rated acting performance of all time. Awful movie, not worthy of the big screen and not worthy of any cable or television channel that has ever played it, including HBO(where I saw it). I am only thankful I didn't actually pay to see one of the most over-rated movies of all time.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
I rented this movie under the impression that it was "Scarecrow 3:Dark Harvest", thinking it was a continuation in the Scarecrow Slayer series (another extremely laughable and all together awful series of movies). I wasn't disappointed though. It was just as awful, if not worse, than what I expected. I was laughing throughout the entire movie. Every piece of bad acting, poorly shot and cut footage, and terrible special effects is what makes this movie worth renting.<br /><br />The special features include a pathetic view into the cast and crew's six months of filming.<br /><br />Favorite line, "The sins of my forefathers! They've trickled down to this very moment of time!"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Surreal film noir released soon after the "real," genre-defining classics "The Maltese Falcon," "Double Indemnity" and "The Postman Always Rings Twice." Welles films shouldn't be evaluated against others. He was playing by different rules. In fact, he was playing. This starts where other femme fatale films leave off, so the vaguely logical (but interesting) whodunit is embellished with a display of Wellesian scenes (typical rapid-fire style), dialog (lots of "hard-boiled" philosophy), and unusual acting (good Hayworth presumably intentionally one-dimensional). To Welles "genre" may have meant "formula" but he seemed to like using "mysteries" as backgrounds for his "entertainments."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
A very funny movie. Michael Douglas' "do" is worth watching this flick for if for no other reason. I'd like to see him do more of these low life roles. He was terrific, as were all the performers.<br /><br />The film struck me right off as an American Roshomon, only funnier and easier to watch because it was in American and didn't need no stinkin subtitles!<br /><br />In a funny movie with a laugh every minute or so, two of the best were with John Goodman (not someone I am crazy about) - 1. He is telling the priest about Jewel doing something he liked and says "I had to wipe the smile off my face." The visual shows he is not smiling and clearly is a guy who never smiles, but probably doesn't know it. 2. The scene at the end between Goodman, all suited up for Jewel in his cop uniform, and grappling with the be-leathered Reiser hunched over a table... and the two of them then protesting that they are not gay to another character who happens on the scene - this alone deserved a special Comedy Academy Award.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
i watched the longer version and could not take my eyes off the screen. 219 minutes passed and yet it seemed like only an hour had gone by. the characters were very believable and entertaining, and the photography was excellent. the story pulled me in and held my attention. i will definitely watch this again and again. this true story telling at it's best... not Hollywoods usual cheap thrills and skin deep glitz. i've seen a quite a lot of reviews on this movie. most seem to pan the film or give it faint praise. basically, it's a great film that received unfairly harsh reviews. watch it for yourself with an open mind. if you like westerns, historic period pieces, albeit historically inaccurate you'll enjoy the movie. Superb!!! 10/10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
Name: count, Length: 49582, dtype: int64
sentiment
1    25000
0    25000
Name: count, dtype: int64

In [72]:
df

                                                  review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production. <br /><br />The...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically there's a family where a little boy ...          0
4      Petter Mattei's "Love in the Time of Money" is...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  I'm going to have to disagree with the previou...          0
49999  No one expects the Star Trek movies to be high...          0

[50000 rows x 2 columns]

In [73]:
df['review'] = df['review'].str.lower()

In [74]:
df

                                                  review  sentiment
0      one of the other reviewers has mentioned that ...          1
1      a wonderful little production. <br /><br />the...          1
2      i thought this was a wonderful way to spend ti...          1
3      basically there's a family where a little boy ...          0
4      petter mattei's "love in the time of money" is...          1
...                                                  ...        ...
49995  i thought this movie did a down right good job...          1
49996  bad plot, bad dialogue, bad acting, idiotic di...          0
49997  i am a catholic taught in parochial elementary...          0
49998  i'm going to have to disagree with the previou...          0
49999  no one expects the star trek movies to be high...          0

[50000 rows x 2 columns]

In [75]:
df['review'] = df['review'].str.replace(r'<br\s*/?>', ' ', regex=True)

df['review'] = df['review'].str.replace(f"[{re.escape(string.punctuation)}]", " ", regex=True)

In [76]:
df

                                                  review  sentiment
0      one of the other reviewers has mentioned that ...          1
1      a wonderful little production    the filming t...          1
2      i thought this was a wonderful way to spend ti...          1
3      basically there s a family where a little boy ...          0
4      petter mattei s  love in the time of money  is...          1
...                                                  ...        ...
49995  i thought this movie did a down right good job...          1
49996  bad plot  bad dialogue  bad acting  idiotic di...          0
49997  i am a catholic taught in parochial elementary...          0
49998  i m going to have to disagree with the previou...          0
49999  no one expects the star trek movies to be high...          0

[50000 rows x 2 columns]

**Model Preparation and training**

In [77]:
df['tokens'] = df['review'].apply(word_tokenize)

In [78]:
df

,review,sentiment,tokens
0,one of the other reviewers has mentioned that ...,1,"[one, of, the, other, reviewers, has, mentione..."
1,a wonderful little production the filming t...,1,"[a, wonderful, little, production, the, filmin..."
2,i thought this was a wonderful way to spend ti...,1,"[i, thought, this, was, a, wonderful, way, to,..."
3,basically there s a family where a little boy ...,0,"[basically, there, s, a, family, where, a, lit..."
4,petter mattei s love in the time of money is...,1,"[petter, mattei, s, love, in, the, time, of, m..."
...,...,...,...
49995,i thought this movie did a down right good job...,1,"[i, thought, this, movie, did, a, down, right,..."
49996,bad plot bad dialogue bad acting idiotic di...,0,"[bad, plot, bad, dialogue, bad, acting, idioti..."
49997,i am a catholic taught in parochial elementary...,0,"[i, am, a, catholic, taught, in, parochial, el..."
49998,i m going to have to disagree with the previou...,0,"[i, m, going, to, have, to, disagree, with, th..."
49999,no one expects the star trek movies to be high...,0,"[no, one, expects, the, star, trek, movies, to..."

In [79]:
stop_words = set(stopwords.words('english'))
df['tokens'] = df['tokens'].apply(lambda x : [word for word in x if word not in stop_words])

In [80]:
df

,review,sentiment,tokens
0,one of the other reviewers has mentioned that ...,1,"[one, reviewers, mentioned, watching, 1, oz, e..."
1,a wonderful little production the filming t...,1,"[wonderful, little, production, filming, techn..."
2,i thought this was a wonderful way to spend ti...,1,"[thought, wonderful, way, spend, time, hot, su..."
3,basically there s a family where a little boy ...,0,"[basically, family, little, boy, jake, thinks,..."
4,petter mattei s love in the time of money is...,1,"[petter, mattei, love, time, money, visually, ..."
...,...,...,...
49995,i thought this movie did a down right good job...,1,"[thought, movie, right, good, job, creative, o..."
49996,bad plot bad dialogue bad acting idiotic di...,0,"[bad, plot, bad, dialogue, bad, acting, idioti..."
49997,i am a catholic taught in parochial elementary...,0,"[catholic, taught, parochial, elementary, scho..."
49998,i m going to have to disagree with the previou...,0,"[going, disagree, previous, comment, side, mal..."
49999,no one expects the star trek movies to be high...,0,"[one, expects, star, trek, movies, high, art, ..."

In [ ]:
lemmatizer = WorldNetLemmatizer()
df['tokens'] = df['tokens'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

In [82]:
df['cleaned_content'] = df['tokens'].apply(lambda x: ' '.join(x))

In [83]:
df

,review,sentiment,tokens,cleaned_content
0,one of the other reviewers has mentioned that ...,1,"[one, reviewers, mentioned, watching, 1, oz, e...",one reviewers mentioned watching 1 oz episode ...
1,a wonderful little production the filming t...,1,"[wonderful, little, production, filming, techn...",wonderful little production filming technique ...
2,i thought this was a wonderful way to spend ti...,1,"[thought, wonderful, way, spend, time, hot, su...",thought wonderful way spend time hot summer we...
3,basically there s a family where a little boy ...,0,"[basically, family, little, boy, jake, thinks,...",basically family little boy jake thinks zombie...
4,petter mattei s love in the time of money is...,1,"[petter, mattei, love, time, money, visually, ...",petter mattei love time money visually stunnin...
...,...,...,...,...
49995,i thought this movie did a down right good job...,1,"[thought, movie, right, good, job, creative, o...",thought movie right good job creative original...
49996,bad plot bad dialogue bad acting idiotic di...,0,"[bad, plot, bad, dialogue, bad, acting, idioti...",bad plot bad dialogue bad acting idiotic direc...
49997,i am a catholic taught in parochial elementary...,0,"[catholic, taught, parochial, elementary, scho...",catholic taught parochial elementary schools n...
49998,i m going to have to disagree with the previou...,0,"[going, disagree, previous, comment, side, mal...",going disagree previous comment side maltin on...
49999,no one expects the star trek movies to be high...,0,"[one, expects, star, trek, movies, high, art, ...",one expects star trek movies high art fans exp...

In [85]:
X = df['cleaned_content']
y = df['sentiment']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [96]:
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [98]:
print(X_train_tfidf)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3896945 stored elements and shape (40000, 92748)>
  Coords	Values
  (0, 44817)	0.0553957773564843
  (0, 5553)	0.06889020089637252
  (0, 50527)	0.0943298923652737
  (0, 30088)	0.06850074703817474
  (0, 72088)	0.06905624574848983
  (0, 51133)	0.08212254589246512
  (0, 80202)	0.08673880181804997
  (0, 33350)	0.05620080391851769
  (0, 51393)	0.08164023189303796
  (0, 61145)	0.10932415677332158
  (0, 1201)	0.09842060413384277
  (0, 53225)	0.04049575049484898
  (0, 17003)	0.08603892598393467
  (0, 3412)	0.02860044292426879
  (0, 77688)	0.05521326732819235
  (0, 82288)	0.030671441477734245
  (0, 58196)	0.07566974808286203
  (0, 22777)	0.06827922096161419
  (0, 14444)	0.03132574119117814
  (0, 48260)	0.03231104044576024
  (0, 21864)	0.060319958340330875
  (0, 88451)	0.07058689486618491
  (0, 40536)	0.06068279007982906
  (0, 13214)	0.04867923154720344
  (0, 36726)	0.051022293362639484
  :	:
  (39999, 66907)	0.08837757553598305
  (39999, 40928)	0.1111661274098959
  (39999, 20903)	0.09975648290187031
  (39999, 11766)	0.08949950901457475
  (39999, 43547)	0.08531479545102162
  (39999, 83707)	0.1375812523056562
  (39999, 1948)	0.2421403882013754
  (39999, 27933)	0.13816512040557297
  (39999, 22285)	0.11345041947767903
  (39999, 82500)	0.095107549
  (39999, 38106)	0.13498872921343139
  (39999, 41830)	0.14546113473941083
  (39999, 64006)	0.13236083683729502
  (39999, 71242)	0.13794448212770327
  (39999, 28445)	0.14845662536992243
  (39999, 22925)	0.11285839285685303
  (39999, 14634)	0.18226762459156803
  (39999, 51239)	0.1420938210715723
  (39999, 81745)	0.14596904373712516
  (39999, 31680)	0.13466777108399397
  (39999, 59516)	0.17082522706734898
  (39999, 29152)	0.1509809666065844
  (39999, 35425)	0.1858449088304053
  (39999, 22755)	0.17053419956538948
  (39999, 16939)	0.23255697618519924

In [99]:
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [101]:
y_pred = model.predict(X_test_tfidf)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.88      0.87      4961
           1       0.88      0.85      0.86      5039

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000

**Testons notre modèle !**

In [105]:
new_data = ["it's a good movie !"]

new_data = [comment.lower() for comment in new_data]

new_data = [comment.translate(str.maketrans(string.punctuation, ' ' * len(string.punctuation))) for comment in new_data]

new_data = [re.sub(r'\s+', ' ', comment.strip()) for comment in new_data]

new_data_tfidf = vectorizer.transform(new_data)

prediction = model.predict(new_data_tfidf)
prediction_proba = model.predict_proba(new_data_tfidf)

print("Prediction : ", prediction[0])
print("Probabilities :", prediction_proba)

Prediction :  1
Probabilities : [[0.48308309 0.51691691]]