**Bienvenue dans ce Jupyter Notebook destiné à effectuer une analyse des sentiments à partir d'un dataset en Python**

In [1]:
!pip install nltk --break-system-packages
!pip install scikit-learn pandas joblib --break-system-packages
import sys
!{sys.executable} -m pip install pandas matplotlib numpy scikit-learn nltk --break-system-packages

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in /home/joris/.local/lib/python3.12/site-packages (3.9.3)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from nltk) (8.1.6)
Requirement already satisfied: joblib in /usr/lib/python3/dist-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /home/joris/.local/lib/python3.12/site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in /home/joris/.local/lib/python3.12/site-packages (from nltk) (4.67.3)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /usr/lib/python3/dist-packages (1.4.1.post1)
Requirement already satisfied: pandas in /home/joris/.local/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: joblib in /usr/lib/python3/dist-packages (1.3.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/lib/python3/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3/dist-packages (from pandas) (2.8.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/joris/.local/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (3.6.3)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.26.4)
Requirement already satisfied: scikit-learn in /usr/lib/python3/dist-packages (1.4.1.post1)
Requirement already satisfied: nltk in /home/joris/.local/lib/python3.12/site-packages (3.9.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from nltk) (8.1.6)
Requirement already satisfied: joblib in /usr/lib/python3/dist-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /home/joris/.local/lib/python3.12/site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in /home/joris/.local/lib/python3.12/site-packages (from nltk) (4.67.3)

In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
import re
import string

nltk.download('stopwords')  # Pour les mots vides
nltk.download('punkt_tab')  # Pour la tokenisation (déjà fait normalement)
nltk.download('wordnet')    # Pour la lemmatisation (notre prochaine étape !)

/home/joris/.local/lib/python3.12/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.9.0' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/joris/.local/lib/python3.12/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
[nltk_data] Downloading package stopwords to /home/joris/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/joris/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /home/joris/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
df = pd.read_csv('IMDB_Dataset.csv')

In [4]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [5]:
df.shape

(50000, 2)

**Data Preprocessing**

In [6]:
mapping = {'positive': 1, 'negative': 0}

df['sentiment'] = df['sentiment'].map(mapping)

df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [7]:
df.value_counts

<bound method DataFrame.value_counts of                                                   review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production. <br /><br />The...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically there's a family where a little boy ...          0
4      Petter Mattei's "Love in the Time of Money" is...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  I'm going to have to disagree with the previou...          0
49999  No one expects the Star Trek movies to be high...          0

[50000 rows x 2 columns]>

In [8]:
print(df['review'].value_counts())
print(df['sentiment'].value_counts())

review
Loved today's show!!! It was a variety and not solely cooking (which would have been great too). Very stimulating and captivating, always keeping the viewer peeking around the corner to see what was coming up next. She is as down to earth and as personable as you get, like one of us which made the show all the more enjoyable. Special guests, who are friends as well made for a nice surprise too. Loved the 'first' theme and that the audience was invited to play along too. I must admit I was shocked to see her come in under her time limits on a few things, but she did it and by golly I'll be writing those recipes down. Saving time in the kitchen means more time with family. Those who haven't tuned in yet, find out what channel and the time, I assure you that you won't be disappointed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        5
Hilarious, clean, light-hearted, and quote-worthy. What else can you ask for in a film? This is my all-time, number one favorite movie. Ever since I was a little girl, I've dreamed of owning a blue van with flames and an observation bubble.<br /><br />The cliché characters in ridiculous situations are what make this film such great fun. The wonderful comedic chemistry between Stephen Furst (Harold) and Andy Tennant (Melio) make up most of my favorite parts of the movie. And who didn't love the hopeless awkwardness of Flynch? Don't forget the airport antics of Leon's cronies, dressed up as Hari Krishnas: dancing, chanting and playing the tambourine--unbeatable! The clues are genius, the locations are classic, and the plot is timeless.<br /><br />A word to the wise, if you didn't watch this film when you were little, it probably won't win a place in your heart today. But nevertheless give it a chance, you may find that "It doesn't matter what you say, it doesn't matter what you do, you've gotta play."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          4
This show comes up with interesting locations as fast as the travel channel. It is billed as reality but in actuality it is pure prime time soap opera. It's tries to use exotic locales as a facade to bring people into a phony contest & then proceeds to hook viewers on the contestants soap opera style.<br /><br />It also borrows from an early CBS game show pioneer- Beat The Clock- by inventing situations for its contestants to try & overcome. Then it rewards the winner money. If they can spice it up with a little interaction between the characters, even better. While the game format is in slow motion versus Beat The Clock- the real accomplishment of this series is to escape reality. <br /><br />This show has elements of several types of successful past programs. Reality television, hardly, but if your hooked on the contestants, locale or contest, this is your cup of tea. If your not, this entire series is as I say, drivel dripping with gravy. It is another show hiding behind the reality label which is the trend it started in 2000.<br /><br />It is slick & well produced, so it might last a while yet. After all, so do re-runs of Gilligan's Island, Green Acres, The Beverly Hillbillies & The Brady Bunch. This just doesn't employ professional actors. The intelligence level is about the same.                                                                                                                                                                                                                                                                                                                                                                                                                      3
Nickelodeon has gone down the toilet. They have kids saying things like "Oh my God!" and "We're screwed"<br /><br />This show promotes hate for people who aren't good looking, or aren't in the in crowd. It say that sexual promiscuity is alright, by having girls slobbering over shirtless boys. Not to mention the overweight boy who takes off his shirt. The main characters basically shun anyone out of the ordinary. Carly's friend Sam, who may be a lesbian, beats the snot out of anybody that crosses her path, which says it's alright to be a b**ch. This show has so much negativity in it that nobody should watch it! I give it a 0 out of 10!!!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            3
You do realize that you've been watching the EXACT SAME SHOW for eight years, right? I could understand the initial curiosity of seeing strangers co-exist on an Island, but you'd think that after watching unkempt, stink-ladened heroes run roughshod through the bush with an egg on a spoon for half a decade would be enough to get you to commit to something a little more original (and interesting).<br /><br />And I'm not even speaking of the shows validity which for the record I find questionable. It's just hard to suspend disbelief for "Bushy Bill" eating a rat when the entire crew of producers and camera people are housed in an air conditioned make-shift bio-dome sipping frosty mochcinno's with moxy.<br /><br />What's the appeal here? I don't care about these people or their meandering lives. I just don't get it. But if you DO find yourself being captivated by hairy, unwashed people, I suggest you turn off your TV and just take a trip to your local bus station where you can see people like this in their TRUE habitat. They call them HOMELESS PEOPLE, and free of charge, you can sit back and marvel in their uncanny ability to retrieve various cigarette debris from a plethora of garbage canisters, eventually striking "pay-dirt" and fashioning a homemade Dr. Frankenstein-styled cancer-stick, all the while begging people for change for food when the stink of "Aqua Velva" on their breath is enough to suggest otherwise. And the best part? Much like Survivor, every week one member of the tribe "Leaves" the "Island" when they are unceremoniously sent packing to the local Institution when the frightening unmedicated state of full-blown schizophrenia kicks into gear! Now THAT'S ENTERTAINMENT!    3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
I thought this movie did a down right good job. It wasn't as creative or original as the first, but who was expecting it to be. It was a whole lotta fun. the more i think about it the more i like it, and when it comes out on DVD I'm going to pay the money for it very proudly, every last cent. Sharon Stone is great, she always is, even if her movie is horrible(Catwoman), but this movie isn't, this is one of those movies that will be underrated for its lifetime, and it will probably become a classic in like 20 yrs. Don't wait for it to be a classic, watch it now and enjoy it. Don't expect a masterpiece, or something thats gripping and soul touching, just allow yourself to get out of your life and get yourself involved in theirs.<br /><br />All in all, this movie is entertaining and i recommend people who haven't seen it see it, because what the critics and box office say doesn't always count, see it for yourself, you never know, you might just enjoy it. I tip my hat to this movie<br /><br />8/10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
Bad plot, bad dialogue, bad acting, idiotic directing, the annoying porn groove soundtrack that ran continually over the overacted script, and a crappy copy of the VHS cannot be redeemed by consuming liquor. Trust me, because I stuck this turkey out to the end. It was so pathetically bad all over that I had to figure it was a fourth-rate spoof of Springtime for Hitler.<br /><br />The girl who played Janis Joplin was the only faint spark of interest, and that was only because she could sing better than the original.<br /><br />If you want to watch something similar but a thousand times better, then watch Beyond The Valley of The Dolls.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
I am a Catholic taught in parochial elementary schools by nuns, taught by Jesuit priests in high school & college. I am still a practicing Catholic but would not be considered a "good Catholic" in the church's eyes because I don't believe certain things or act certain ways just because the church tells me to.<br /><br />So back to the movie...its bad because two people are killed by this nun who is supposed to be a satire as the embodiment of a female religious figurehead. There is no comedy in that and the satire is not done well by the over acting of Diane Keaton. I never saw the play but if it was very different from this movies then it may be good.<br /><br />At first I thought the gun might be a fake and the first shooting all a plan by the female lead of the four former students as an attempt to demonstrate Sister Mary's emotional and intellectual bigotry of faith. But it turns out the bullets were real and the story has tragedy...the tragedy of loss of life (besides the two former students...the lives of the aborted babies, the life of the student's mom), the tragedy of dogmatic authority over love of people, the tragedy of organized religion replacing true faith in God. This is what is wrong with today's Islam, and yesterday's Judaism and Christianity.                                                                                                                                                                                                                                                                                                                                                                                                                                                1
I'm going to have to disagree with the previous comment and side with Maltin on this one. This is a second rate, excessively vicious Western that creaks and groans trying to put across its central theme of the Wild West being tamed and kicked aside by the steady march of time. It would like to be in the tradition of "Butch Cassidy and the Sundance Kid", but lacks that film's poignancy and charm. Andrew McLaglen's direction is limp, and the final 30 minutes or so are a real botch, with some incomprehensible strategy on the part of heroes Charlton Heston and Chris Mitchum. (Someone give me a holler if you can explain to me why they set that hillside on fire.) There was something callous about the whole treatment of the rape scene, and the woman's reaction afterwards certainly did not ring true. Coburn is plenty nasty as the half breed escaped convict out for revenge, but all of his fellow escapees are underdeveloped (they're like bowling pins to be knocked down one by one as the story lurches forward). Michael Parks gives one of his typically shifty, lethargic, mumbling performances, but in this case it was appropriate as his modern style sheriff symbolizes the complacency that technological progress can bring about.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
No one expects the Star Trek movies to be high art, but the fans do expect a movie that is as good as some of the best episodes. Unfortunately, this movie had a muddled, implausible plot that just left me cringing - this is by far the worst of the nine (so far) movies. Even the chance to watch the well known characters interact in another movie can't save this movie - including the goofy scenes with Kirk, Spock and McCoy at Yosemite.<br /><br />I would say this movie is not worth a rental, and hardly worth watching, however for the True Fan who needs to see all the movies, renting this movie is about the only way you'll see it - even the cable channels avoid this movie.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
Name: count, Length: 49582, dtype: int64
sentiment
1    25000
0    25000
Name: count, dtype: int64

In [9]:
df

                                                  review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production. <br /><br />The...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically there's a family where a little boy ...          0
4      Petter Mattei's "Love in the Time of Money" is...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  I'm going to have to disagree with the previou...          0
49999  No one expects the Star Trek movies to be high...          0

[50000 rows x 2 columns]

In [10]:
df['review'] = df['review'].str.lower()

In [11]:
df

                                                  review  sentiment
0      one of the other reviewers has mentioned that ...          1
1      a wonderful little production. <br /><br />the...          1
2      i thought this was a wonderful way to spend ti...          1
3      basically there's a family where a little boy ...          0
4      petter mattei's "love in the time of money" is...          1
...                                                  ...        ...
49995  i thought this movie did a down right good job...          1
49996  bad plot, bad dialogue, bad acting, idiotic di...          0
49997  i am a catholic taught in parochial elementary...          0
49998  i'm going to have to disagree with the previou...          0
49999  no one expects the star trek movies to be high...          0

[50000 rows x 2 columns]

In [12]:
df['review'] = df['review'].str.replace(r'<br\s*/?>', ' ', regex=True)

df['review'] = df['review'].str.replace(f"[{re.escape(string.punctuation)}]", " ", regex=True)

In [13]:
df

                                                  review  sentiment
0      one of the other reviewers has mentioned that ...          1
1      a wonderful little production    the filming t...          1
2      i thought this was a wonderful way to spend ti...          1
3      basically there s a family where a little boy ...          0
4      petter mattei s  love in the time of money  is...          1
...                                                  ...        ...
49995  i thought this movie did a down right good job...          1
49996  bad plot  bad dialogue  bad acting  idiotic di...          0
49997  i am a catholic taught in parochial elementary...          0
49998  i m going to have to disagree with the previou...          0
49999  no one expects the star trek movies to be high...          0

[50000 rows x 2 columns]

**Model Preparation and training**

In [14]:
df['tokens'] = df['review'].apply(word_tokenize)

In [15]:
df

,review,sentiment,tokens
0,one of the other reviewers has mentioned that ...,1,"[one, of, the, other, reviewers, has, mentione..."
1,a wonderful little production the filming t...,1,"[a, wonderful, little, production, the, filmin..."
2,i thought this was a wonderful way to spend ti...,1,"[i, thought, this, was, a, wonderful, way, to,..."
3,basically there s a family where a little boy ...,0,"[basically, there, s, a, family, where, a, lit..."
4,petter mattei s love in the time of money is...,1,"[petter, mattei, s, love, in, the, time, of, m..."
...,...,...,...
49995,i thought this movie did a down right good job...,1,"[i, thought, this, movie, did, a, down, right,..."
49996,bad plot bad dialogue bad acting idiotic di...,0,"[bad, plot, bad, dialogue, bad, acting, idioti..."
49997,i am a catholic taught in parochial elementary...,0,"[i, am, a, catholic, taught, in, parochial, el..."
49998,i m going to have to disagree with the previou...,0,"[i, m, going, to, have, to, disagree, with, th..."
49999,no one expects the star trek movies to be high...,0,"[no, one, expects, the, star, trek, movies, to..."

In [16]:
stop_words = set(stopwords.words('english'))
df['tokens'] = df['tokens'].apply(lambda x : [word for word in x if word not in stop_words])

In [17]:
df

,review,sentiment,tokens
0,one of the other reviewers has mentioned that ...,1,"[one, reviewers, mentioned, watching, 1, oz, e..."
1,a wonderful little production the filming t...,1,"[wonderful, little, production, filming, techn..."
2,i thought this was a wonderful way to spend ti...,1,"[thought, wonderful, way, spend, time, hot, su..."
3,basically there s a family where a little boy ...,0,"[basically, family, little, boy, jake, thinks,..."
4,petter mattei s love in the time of money is...,1,"[petter, mattei, love, time, money, visually, ..."
...,...,...,...
49995,i thought this movie did a down right good job...,1,"[thought, movie, right, good, job, creative, o..."
49996,bad plot bad dialogue bad acting idiotic di...,0,"[bad, plot, bad, dialogue, bad, acting, idioti..."
49997,i am a catholic taught in parochial elementary...,0,"[catholic, taught, parochial, elementary, scho..."
49998,i m going to have to disagree with the previou...,0,"[going, disagree, previous, comment, side, mal..."
49999,no one expects the star trek movies to be high...,0,"[one, expects, star, trek, movies, high, art, ..."

In [18]:
lemmatizer = WordNetLemmatizer()
df['tokens'] = df['tokens'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

In [19]:
df['cleaned_content'] = df['tokens'].apply(lambda x: ' '.join(x))

In [20]:
df

,review,sentiment,tokens,cleaned_content
0,one of the other reviewers has mentioned that ...,1,"[one, reviewer, mentioned, watching, 1, oz, ep...",one reviewer mentioned watching 1 oz episode h...
1,a wonderful little production the filming t...,1,"[wonderful, little, production, filming, techn...",wonderful little production filming technique ...
2,i thought this was a wonderful way to spend ti...,1,"[thought, wonderful, way, spend, time, hot, su...",thought wonderful way spend time hot summer we...
3,basically there s a family where a little boy ...,0,"[basically, family, little, boy, jake, think, ...",basically family little boy jake think zombie ...
4,petter mattei s love in the time of money is...,1,"[petter, mattei, love, time, money, visually, ...",petter mattei love time money visually stunnin...
...,...,...,...,...
49995,i thought this movie did a down right good job...,1,"[thought, movie, right, good, job, creative, o...",thought movie right good job creative original...
49996,bad plot bad dialogue bad acting idiotic di...,0,"[bad, plot, bad, dialogue, bad, acting, idioti...",bad plot bad dialogue bad acting idiotic direc...
49997,i am a catholic taught in parochial elementary...,0,"[catholic, taught, parochial, elementary, scho...",catholic taught parochial elementary school nu...
49998,i m going to have to disagree with the previou...,0,"[going, disagree, previous, comment, side, mal...",going disagree previous comment side maltin on...
49999,no one expects the star trek movies to be high...,0,"[one, expects, star, trek, movie, high, art, f...",one expects star trek movie high art fan expec...

In [21]:
X = df['cleaned_content']
y = df['sentiment']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [22]:
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [23]:
print(X_train_tfidf)

  (0, 33269)	0.08073432328927974
  (0, 76391)	0.040834115741908206
  (0, 48)	0.037495350214899394
  (0, 8397)	0.07995458147051107
  (0, 64633)	0.05185509167800472
  (0, 78736)	0.06917205403294709
  (0, 58959)	0.07145820254858934
  (0, 21433)	0.10821558501607108
  (0, 48072)	0.07425783005830162
  (0, 1896)	0.04955780247201142
  (0, 58409)	0.07309352382082258
  (0, 26213)	0.06880038235128134
  (0, 51606)	0.08023253204719326
  (0, 22358)	0.08378389070178857
  (0, 81913)	0.0673147256391525
  (0, 37116)	0.0664218323102826
  (0, 18770)	0.04657959951727415
  (0, 3191)	0.05038275600409468
  (0, 56752)	0.03217076613907953
  (0, 30767)	0.03506414259768321
  (0, 1902)	0.03734638428011066
  (0, 38548)	0.05838542014842136
  (0, 11270)	0.07735758169765514
  (0, 35398)	0.05945922525535389
  (0, 72928)	0.08731993462487558
  :	:
  (39999, 60347)	0.07085474449236132
  (39999, 45402)	0.05074593982724316
  (39999, 67019)	0.09026094429302929
  (39999, 65674)	0.08714659919878415
  (39999, 45329)	0.08635644398351396
  (39999, 31803)	0.1734972392772578
  (39999, 45098)	0.05825272996346454
  (39999, 56504)	0.08168742653939817
  (39999, 7646)	0.1671638269582781
  (39999, 16395)	0.12021927721095266
  (39999, 3243)	0.08376295154652064
  (39999, 70984)	0.10947957286062712
  (39999, 24072)	0.22245898193989036
  (39999, 31278)	0.04793828519807384
  (39999, 25298)	0.10291271718571039
  (39999, 70932)	0.05260662427510771
  (39999, 73061)	0.10526352566226019
  (39999, 1902)	0.07268625955873062
  (39999, 49665)	0.3489231570494776
  (39999, 8543)	0.07865612015520093
  (39999, 74773)	0.09246035559121162
  (39999, 1862)	0.12381057147613506
  (39999, 49787)	0.05527827069830293
  (39999, 43793)	0.06497866554471568
  (39999, 13144)	0.15397587396275075

In [24]:
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [25]:
y_pred = model.predict(X_test_tfidf)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.88      0.87      4961
           1       0.88      0.85      0.86      5039

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000

**Testons notre modèle !**

In [26]:
new_data = ["I didn't like this movie ! "]

new_data = [comment.lower() for comment in new_data]

new_data = [comment.translate(str.maketrans(string.punctuation, ' ' * len(string.punctuation))) for comment in new_data]

new_data = [re.sub(r'\s+', ' ', comment.strip()) for comment in new_data]

new_data_tfidf = vectorizer.transform(new_data)

prediction = model.predict(new_data_tfidf)
prediction_proba = model.predict_proba(new_data_tfidf)

print("Prediction : ", prediction[0])
print("Probabilities :", prediction_proba)

Prediction :  0
Probabilities : [[0.50360005 0.49639995]]

In [27]:
import joblib

joblib.dump(model, 'sentiment_model.pkl')
joblib.dump(vectorizer, 'tfidf_vectorizer.pkl')

['tfidf_vectorizer.pkl']